# 子频道创建配置

# 子频道列表，可以配置多个子频道
channels:
  - name: "文字频道" # 子频道名称
    type: 0 # 子频道类型：0文字频道，1语音频道
    parent_id: "0" # 父频道ID，顶级频道为0
    private: 0 # 是否私密：0公开，1私密
    speak: 0 # 发言权限：0所有人，1仅管理员

# 服务器ID（可选，如果不填会在运行时提示选择）
guild_id: "" # 留空则会在运行时显示服务器列表供选择
